@startuml

    Title: 1: Patron loan history acceptance flow

            Patron->Biblioteket app: Log in.
            Biblioteket app->Adgangsplatform: Authenticate User.
            Biblioteket app->Patron: Prompt for yes/no to save loan history.
            Patron->Biblioteket app: Yes to save loan history.
            Biblioteket app->FBS: Request Patron ID. (preauthenticate endpoint using CPR).
            Adgangsplatform->Biblioteket app: GUID + CPR.
            Biblioteket app->Subscription WS: Save "Yes to save loan history" + CPR + GUID + Patron ID.

@enduml
@startuml

    Title: 2. Anonymous Loan history web service data accumulation flow
     
            FBS->Service Platform: Daily data dump of loan history (PatronID + PID).
            Service Platform->Danmarks Statistik: Data dump is "sanitized", enriched and anonymized.
            Danmarks Statistik->Faktor: Delivery of statistics based on loan history etc.
            Faktor->Anonymous Loan History WS: Export anonymized loan history.

@enduml
@startuml

    Title: 3: Loan history web service data accumulation flow
         
            FBS->Service Platform: Daily data dump of loan history (PatronID + PID).
            Loanhistory WS->Service Platform: Request latest changes to loan history.
            Service Platform->Loanhistory WS: Return latest changes to loan history.
            Loanhistory WS->Subscription WS: Request list of users with "Yes to save loan history".
            Subscription WS->Loanhistory WS: Return Patron ID for each user with "Yes to save loan history".
            Loanhistory WS->Loanhistory WS: For each user: Extract and save loan history.

@enduml
@startuml

    Title: 4. Patron recommendation flow

            Patron->Biblioteket app: Request recommendations.
            Biblioteket app->Recommendation WS: Request recommendations for Patron X (Patron ID || GUID).
            Recommendation WS->Loanhistory WS: Request loan history for Patron X.
            Loanhistory WS->Recommendation WS: Return loan history for Patron X.
            Recommendation WS->Recommendation WS: Generate recommendations for Patron X. (On the fly || daily)
            Recommendation WS->Biblioteket app: Return recommendations for Patron X (List of PID's).
            Biblioteket app->Patron: Display recommendations.

@enduml