@startuml
    Title: 1. User generated material lists data flow

    Note left of Patron: Prerequisite: Patron and Client are authenticated.
            
    "Patron"->"DDB CMS": Add material to Material List.
    "DDB CMS"->"Material List service": Post - GUID (User id) and PID (material id).

    group IF it is the first use of Material List.
        "Material List service"->"Material List service": Create Material List identified by Patron GUID.
        "Material List service"->"Material List service": Create Material List identified by Patron GUID.
    end

    group ELSE if Patron has used Material List earlier.
        "Material List service"->"DDB CMS": Return - Material added to list.
    end
            
@enduml