@startuml
        Title: 1. User generated material lists data flow

            "DDB CMS"->"Oauth2.login.bib.dk": Request autentication.
            "Oauth2.login.bib.dk"->"DDB CMS": Authentication granted.
            Note left of "Oauth2.login.bib.dk": Return token.
            
            "DDB CMS"->"Openlist": Authenticate with token.
            "Openlist"->"Oauth2.login.bib.dk": Verify token.
            "Oauth2.login.bib.dk"->"Openlist": Token verified.
            "Openlist"->"DDB CMS": Authenticated.

            "Patron"->"DDB CMS": Log in.
            "DDB CMS"->"Adgangsplatform": Request - Authenticate User.
            "Adgangsplatform"->"DDB CMS": Return - Authenticated user.
            
            Note left of Adgangsplatform: Return token.
            
            "DDB CMS"->"Patron": Display - Logged in.
            
            "Patron"->"DDB CMS": Add material to list.
            "DDB CMS"->"Openlist": Post - GUID (User id) + PID (material id).
            "Openlist"->"DDB CMS": Return - Material added to list.
            
@enduml